services:
  # Backend API Service
  - type: web
    name: stockwatch-api
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Dspring.profiles.active=prod -Dserver.port=$PORT -jar target/StockWatch-1.0-SNAPSHOT.jar
    healthCheckPath: /actuator/health
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stockwatch-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: stockwatch-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: stockwatch-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: STOCK_API_KEY
        value: demo
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  # Frontend Service
  - type: web
    name: stockwatch-frontend
    env: node
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/build
    plan: starter
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: stockwatch-api
          property: host

# Database
databases:
  - name: stockwatch-db
    databaseName: stockwatch
    user: stockwatch
    plan: starter
