spring:
  application:
    name: stockwatch

  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

jwt:
  secret: ${JWT_SECRET:mySecretKey1234567890123456789012345678901234567890abcdef}
  expiration: 86400000

stock:
  api:
    base-url: ${STOCK_API_BASE_URL:https://www.alphavantage.co}
    key: ${STOCK_API_KEY}
    fetch-interval: ${STOCK_FETCH_INTERVAL:300000}

logging:
  level:
    org.example: INFO
    org.springframework.security: WARN
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
