spring:
  application:
    name: stockwatch

  datasource:
    url: jdbc:h2:mem:stockwatch
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: false

server:
  port: 8080

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000

stock:
  api:
    base-url: https://www.alphavantage.co
    key: demo
    fetch-interval: 300000

logging:
  level:
    org.example: DEBUG
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
